const ECData = [
  {
    name: "Samaksh Gupta",
    role: "Convenor",
    profilepic: "https://images.prismic.io/ieeemuj/ZnJjw5m069VX13S1_IMG-20240405-WA0024~2-SamakshGupta.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/samakshgupta04",
    github: "https://github.com/AwesomeSam9523",
    instagram: "https://www.instagram.com/samaksh.gupta04/",
  },
  {
    name: "Aditya Rajawat",
    role: "Convenor",
    profilepic: "https://images.prismic.io/ieeemuj/ZoRK1x5LeNNTwulX_AdityaSinghHeadEditorial.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/aditya-singh-rajawat69?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    instagram: "https://www.instagram.com/rajawat_adi19/",
  },
  {
    name: "Kashish Kumar",
    role: "Convenor",
    profilepic: "https://images.prismic.io/ieeemuj/ZurIYLVsGrYSviKx_KashishKumar%2CHeadofEditorial.JPG?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/kashish-kumar-527ba72b3/",
    instagram: "https://www.instagram.com/kashish._kumar_?igsh=MWEzZTQ3dnN4emVtNw%3D%3D&utm_source=qr/",
  },
  {
    name: "Anshika Katare",
    role: "Convenor",
    profilepic:"https://images.prismic.io/ieeemuj/aGjHJnfc4bHWjEhn_AnshikaKatare.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/anshikakatare/",
    instagram: "",
  },
  {
    name: "Tamanna Yadav",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/pranav-bhardwaj-107454206",
    instagram: "https://instagram.com/pranav._.02?igshid=MzNlNGNkZWQ4Mg==",
  },
  {
    name: "Salaj Singh Bisht",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/mohit-hingorani-439265248/",
    instagram:"https://www.instagram.com/mojitowithice/",
  },
  {
    name: "Aryan Verma",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/harshneet-khanna-031505236",
    instagram: "https://www.instagram.com/joy_khanna11/"
  },
  {
    name: "Vinayak Jajoo",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/shreya-saihgal-16a834261/",
    instagram: ""
  },
  {
    name: "Bhavya Jaggi",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/shristikrishna/",
    instagram:"https://instagram.com/_shristi.k_?igshid=OGQ5ZDc2ODk2ZA==",
  },
  {
    name: "Neil Gupta",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/naaddantale",
    instagram: "https://instagram.com/naad.daan__",
  },
  {
    name: "Krish Jaiswal",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/karan-kapoor-843484267",
    instagram:"https://instagram.com/_karan_kapoor._?igshid=NGExMmI2YTkyZg==",
  },
  {
    name: "Tanmay Shah",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/saumya-gupta-8629a5267",
    instagram:"https://instagram.com/saumya.gupta15?igshid=YmMyMTA2M2Y=",
  },
  {
    name: "Shaivi Adesh",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "",
    instagram:"https://www.instagram.com/shashwat_14singh/",
  },
  {
    name: "Devansh Kothari",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/gouri-sharma-1b7911236/",
    instagram:"",
  },
  {
    name: "Khushi Bhatia",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/devishi-817aa1265?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    instagram:"https://www.instagram.com/devishiiimahajann?igsh=MW",
  },
  {
    name: "Ritika",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/competitiveblood/",
    instagram:"https://www.instagram.com/rizzvangi/",
  },
  {
    name: "Guneet Pahwa",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/aaranay-aadi-047572252/",
    instagram:"https://www.instagram.com/aaranayaadi/",
  },
  {
    name: "Tanishk Mittal",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://in.linkedin.com/in/krishnav-gupta-670a7a26a",
    instagram: "https://www.instagram.com/krishnav_g/",
  },
  {
    name: "Shambhavi Sharma",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/praketh-voona-82b34b248",
    instagram:"https://instagram.com/lilprakx?igshid=ZDc4ODBmNjlmNQ==",
  },
  {
    name: "Akshit Gupta",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "http://linkedin.com/in/kunal-singh-70288227a",
    instagram:"https://instagram.com/kkunal97",
  },
  {
    name: "Ishani Arora",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/shivam-shandilya-a4908a247/",
    instagram:"https://www.instagram.com/shi.vam.07",
  },
  {
    name: "Aarav",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/ayana-takshak-4a609324b",
    instagram:"https://instagram.com/ayaannaa.t?igshid=MmIzYWVlNDQ5Yg==",
  },
  {
    name: "Yash Ramnani",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/aGjHJXfc4bHWjEhm_YASHRAMNANI.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/ayush-agrawal-50717124a/",
    instagram: "https://www.instagram.com/_ayush.agrawal_/",
  },
  {
    name: "Atishay Jain",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/aGZsAXfc4bHWjAPg_AtishayJain.jpg?auto=format,compress",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Kanishka Bhatia",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/aGa_zHfc4bHWjB5y_KANISHKA.jpg?auto=format,compress",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Harshit Chadha",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/aGZsLXfc4bHWjAPo_HARSHITCHADHA.jpg?auto=format,compress",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Aarna Pareek",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/aGa_y3fc4bHWjB5w_AarnaPareek.HEIC?auto=format,compress",
    linkedin: "",
    instagram: "",
  },
];

export default ECData;
