const ECData = [
  {
    name: "Rishi Joshi",
    role: "Convenor",
    profilepic: "https://images.prismic.io/ieeemuj/d6afed2e-b0ba-484a-a625-6ce8d905d957_rishipic.webp?auto=compress,format",
    linkedin: "https://www.linkedin.com/in/rishi-joshi-924882200",
    github: "https://github.com/tangorishi",
    instagram: "https://instagram.com/wtfrishiiiii?igshid=ZDc4ODBmNjlmNQ==",
  },
  {
    name: "Lakshita Agrawal",
    role: "Convenor",
    profilepic: "https://images.prismic.io/ieeemuj/ZpJqhh5LeNNTxIal_WhatsAppImage2024-07-13at17.21.51.jpeg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/lakshita-agrawal-b716a4243/",
    instagram: "https://www.instagram.com/lakshita._.agrawal/",
  },
  {
    name: "Ananta Taneja",
    role: "Convenor",
    profilepic: "https://images.prismic.io/ieeemuj/ZrPy80aF0TcGIw6S_wie_chair.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/ananta-t-690431211?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    instagram: "https://www.instagram.com/at_1920_28?igsh=OGQ5ZDc2ODk2ZA==",
  },
  {
    name: "Satvika Arora",
    role: "Convenor",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Pranav Bhardwaj",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZqoHjh5LeNNTxpJj_pranavbhaiya.png?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/pranav-bhardwaj-107454206",
    instagram: "https://instagram.com/pranav._.02?igshid=MzNlNGNkZWQ4Mg==",
  },
  {
    name: "Mohit Hingorani",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnPxv5m069VX16JG_1000005233-02.jpeg.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/mohit-hingorani-439265248/",
    instagram:"https://www.instagram.com/mojitowithice/",
  },
  {
    name: "Harshneet Khanna",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnHa-Zm069VX125x_WhatsAppImage2024-06-19at00.36.57_762311f2.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/harshneet-khanna-031505236",
    instagram: "https://www.instagram.com/joy_khanna11/"
  },
  {
    name: "Shreya Saihgal",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/3b73b918-8182-45ce-b764-18791e7bf44f_Shreya+Saihgal.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/shreya-saihgal-16a834261/",
    instagram: ""
  },
  {
    name: "Shristi Krishna",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/8a647216-f4e2-4258-9879-5d90ed10fd0c_SHRISTI+KRISHNA.jpg",
    linkedin: "https://www.linkedin.com/in/shristikrishna/",
    instagram:"https://instagram.com/_shristi.k_?igshid=OGQ5ZDc2ODk2ZA==",
  },
  {
    name: "Naad Dantale",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnJujpm069VX13Us_WhatsAppImage2024-06-19at10.58.58_c139107e.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/naaddantale",
    instagram: "https://instagram.com/naad.daan__",
  },
  {
    name: "Karan Kapoor",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/e18134c6-fb64-4659-8bc3-df3224374bc6_Karan+Kapoor_.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/karan-kapoor-843484267",
    instagram:"https://instagram.com/_karan_kapoor._?igshid=NGExMmI2YTkyZg==",
  },
  {
    name: "Saumya Gupta",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZrPzckaF0TcGIw6a_wie_vice.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/saumya-gupta-8629a5267",
    instagram:"https://instagram.com/saumya.gupta15?igshid=YmMyMTA2M2Y=",
  },
  {
    name: "Shashwat Singh",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZrPzMEaF0TcGIw6U_wie_secretary.jpg?auto=format,compress",
    linkedin: "",
    instagram:"https://www.instagram.com/shashwat_14singh/",
  },
  {
    name: "Gouri Sharma",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZrP5y0aF0TcGIw8U_GouriSharma-JointHeadofGraphicDesign.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/gouri-sharma-1b7911236/",
    instagram:"",
  },
  {
    name: "Devishi Mahajan",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZrPzcUaF0TcGIw6Z_wie_treasurer.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/devishi-817aa1265?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    instagram:"https://www.instagram.com/devishiiimahajann?igsh=MW",
  },
  {
    name: "Shivani Singh",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZrPzMEaF0TcGIw6T_wie_hrd.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/competitiveblood/",
    instagram:"https://www.instagram.com/rizzvangi/",
  },
  {
    name: "Aaranay Aadi",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZrPzb0aF0TcGIw6Y_wie_tc.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/aaranay-aadi-047572252/",
    instagram:"https://www.instagram.com/aaranayaadi/",
  },
  {
    name: "Krishnav Gupta",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZpKi0B5LeNNTxIto_WhatsAppImage2024-07-13at21.21.52.jpeg?auto=format,compress",
    linkedin: "https://in.linkedin.com/in/krishnav-gupta-670a7a26a",
    instagram: "https://www.instagram.com/krishnav_g/",
  },
  {
    name: "Praketh Voona",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZpJ1_R5LeNNTxIm7_WhatsAppImage2024-07-13at18.10.42.jpeg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/praketh-voona-82b34b248",
    instagram:"https://instagram.com/lilprakx?igshid=ZDc4ODBmNjlmNQ==",
  },
  {
    name: "Kunal Kumar",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZpJwaR5LeNNTxIcY_WhatsAppImage2024-07-13at17.45.12.jpeg?auto=format,compress",
    linkedin: "http://linkedin.com/in/kunal-singh-70288227a",
    instagram:"https://instagram.com/kkunal97",
  },
  {
    name: "Shivam Shandilya",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/c233176a-0adf-4625-a462-f4448632ed95_SHIVAM+SHANDILYA.jpg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/shivam-shandilya-a4908a247/",
    instagram:"https://www.instagram.com/shi.vam.07",
  },
  {
    name: "Ayana Takshak",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/692a3910-0b46-46fe-8e75-33afb186d14e_Ayana+takshak.jpeg?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/ayana-takshak-4a609324b",
    instagram:"https://instagram.com/ayaannaa.t?igshid=MmIzYWVlNDQ5Yg==",
  },
  {
    name: "Ayush Agrawal",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZvU4zrVsGrYSwBsg_IMG_8066.JPG?auto=format,compress",
    linkedin: "https://www.linkedin.com/in/ayush-agrawal-50717124a/",
    instagram: "https://www.instagram.com/_ayush.agrawal_/",
  },
  {
    name: "Rohan Arora",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Aditi Sharma",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Mithilesh Mudaliar",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Aryan Jhammnani",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Pavni Jain",
    role: "Director",
    profilepic: "https://images.prismic.io/ieeemuj/ZnkWFpbWFboweynT_profile_placeholder.png?auto=format,compress",
    linkedin: "",
    instagram: "",
  }
];

export default ECData;
